//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""dd0de2d4-6e6d-4a5e-80bb-aa7dd81f63e2"",
            ""actions"": [
                {
                    ""name"": ""DirectionalThrusters"",
                    ""type"": ""Value"",
                    ""id"": ""3fa23ed1-5c0e-45b1-854e-cbe1bdc5c8e2"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TakeoffThruster"",
                    ""type"": ""Button"",
                    ""id"": ""bf622df8-46af-43aa-a236-655a12e113df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""345e7c0f-b9cf-42ab-a75e-e9b4710c69d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotationalThrusters"",
                    ""type"": ""Value"",
                    ""id"": ""2fc68820-b3f7-4d19-bd78-a8e7ebad1c3b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""490df92f-4731-4d65-8594-ba37e4c687c7"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalThrusters"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a6a9984d-befa-4256-b7a3-f646c378b07c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalThrusters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f5bf89d6-3441-4e6c-b91c-bfb89ba278cc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalThrusters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cd8b04b0-80fe-4583-9bf5-e2fe3d55c2b7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalThrusters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fa99d263-e1b1-455d-b0fa-4f2bea6e06fe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalThrusters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0e618983-378a-4859-9d42-8de2a77a144f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeoffThruster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a00a94a-45c0-445a-b168-482a52fe567f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""cb6ac9de-6cf1-46c6-962f-e10d076df372"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotationalThrusters"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""978ca782-7436-4a62-b0b0-f6dfb5793616"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotationalThrusters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0a0bc3a5-e8a7-4e12-ba11-888f9f194989"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotationalThrusters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_DirectionalThrusters = m_Player.FindAction("DirectionalThrusters", throwIfNotFound: true);
        m_Player_TakeoffThruster = m_Player.FindAction("TakeoffThruster", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_RotationalThrusters = m_Player.FindAction("RotationalThrusters", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_DirectionalThrusters;
    private readonly InputAction m_Player_TakeoffThruster;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_RotationalThrusters;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @DirectionalThrusters => m_Wrapper.m_Player_DirectionalThrusters;
        public InputAction @TakeoffThruster => m_Wrapper.m_Player_TakeoffThruster;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @RotationalThrusters => m_Wrapper.m_Player_RotationalThrusters;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @DirectionalThrusters.started += instance.OnDirectionalThrusters;
            @DirectionalThrusters.performed += instance.OnDirectionalThrusters;
            @DirectionalThrusters.canceled += instance.OnDirectionalThrusters;
            @TakeoffThruster.started += instance.OnTakeoffThruster;
            @TakeoffThruster.performed += instance.OnTakeoffThruster;
            @TakeoffThruster.canceled += instance.OnTakeoffThruster;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @RotationalThrusters.started += instance.OnRotationalThrusters;
            @RotationalThrusters.performed += instance.OnRotationalThrusters;
            @RotationalThrusters.canceled += instance.OnRotationalThrusters;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @DirectionalThrusters.started -= instance.OnDirectionalThrusters;
            @DirectionalThrusters.performed -= instance.OnDirectionalThrusters;
            @DirectionalThrusters.canceled -= instance.OnDirectionalThrusters;
            @TakeoffThruster.started -= instance.OnTakeoffThruster;
            @TakeoffThruster.performed -= instance.OnTakeoffThruster;
            @TakeoffThruster.canceled -= instance.OnTakeoffThruster;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @RotationalThrusters.started -= instance.OnRotationalThrusters;
            @RotationalThrusters.performed -= instance.OnRotationalThrusters;
            @RotationalThrusters.canceled -= instance.OnRotationalThrusters;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnDirectionalThrusters(InputAction.CallbackContext context);
        void OnTakeoffThruster(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnRotationalThrusters(InputAction.CallbackContext context);
    }
}
